AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Full LLM Stack

Parameters:
  QueueName:
    Type: String
    Description: Name of the main SQS queue
    Default: llm-queue
  TasksQueueName:
    Type: String
    Description: Name of the tasks SQS queue
    Default: llm-queue-tasks
  KPIQueueName:
    Type: String
    Description: Name of the KPI SQS queue
    Default: llm-queue-kpi
  UsecaseQueueName:
    Type: String
    Description: Name of the usecase SQS queue
    Default: llm-queue-usecase
  BusinessAreasQueueName:
    Type: String
    Description: Name of the business areas SQS queue
    Default: llm-queue-businessareas
  IndustryQueueName:
    Type: String
    Description: Name of the industry SQS queue
    Default: llm-queue-industry
  LogoQueueName:
    Type: String
    Description: Name of the logo SQS queue
    Default: llm-queue-logo

Resources:
  MyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${QueueName}-dlq"
      MessageRetentionPeriod: 1209600  # 14 days in seconds

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyTasksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref TasksQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyKPIQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref KPIQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyUsecaseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref UsecaseQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyBusinessAreasQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref BusinessAreasQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyIndustryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IndustryQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  MyLogoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref LogoQueueName
      VisibilityTimeout: 1000
      MessageRetentionPeriod: 345600 # 4 days in seconds
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 1

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MySQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MySQSQueue.Arn

  TasksSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyTasksQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyTasksQueue.Arn

  KPISQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyKPIQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyKPIQueue.Arn

  UsecaseSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyUsecaseQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyUsecaseQueue.Arn

  BusinessAreasSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyBusinessAreasQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyBusinessAreasQueue.Arn

  IndustrySQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyIndustryQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyIndustryQueue.Arn

  LogoSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyLogoQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt MyLogoQueue.Arn

  SQSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/sqs/${QueueName}"
      RetentionInDays: 7

  SQSMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref SQSLogGroup
      FilterPattern: ""
      MetricTransformations:
        - MetricNamespace: "SQSMetrics"
          MetricName: "MessageCount"
          MetricValue: "1"

  TasksLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_tasks.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for tasks
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  SolutionsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_solutions.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: lambda for solutions
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp
  KPILambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_kpi.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for KPI processing
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  UsecaseLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_usecase.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for usecase processing
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  BusinessAreaLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_business_areas.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for business areas processing
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  IndustriesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_industry_category.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for industry processing
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  LogoLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_logo.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Lambda for logo processing
      Timeout: 100
      MemorySize: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          AWS_CLOUDFORMATION_STACK_NAME: !Ref AWS::StackName
          SECRET_NAME: llmapp

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: function/package/.
      CompatibleRuntimes:
        - python3.8

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:llmapp-*'
        - PolicyName: SQSReceiveMessagePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: 
                  - !GetAtt MySQSQueue.Arn
                  - !GetAtt MyTasksQueue.Arn
                  - !GetAtt MyKPIQueue.Arn
                  - !GetAtt MyUsecaseQueue.Arn
                  - !GetAtt MyBusinessAreasQueue.Arn
                  - !GetAtt MyIndustryQueue.Arn
                  - !GetAtt MyLogoQueue.Arn

  LambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SolutionsLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MySQSQueue.Arn

  TasksLambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TasksLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyTasksQueue.Arn

  KPILambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KPILambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyKPIQueue.Arn

  UsecaseLambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UsecaseLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyUsecaseQueue.Arn

  BusinessAreaLambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BusinessAreaLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyBusinessAreasQueue.Arn

  IndustriesLambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IndustriesLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyIndustryQueue.Arn

  LogoLambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogoLambda
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MyLogoQueue.Arn


  TasksLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyTasksQueue.Arn
      FunctionName: !Ref TasksLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5

  SQSLambdaTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MySQSQueue.Arn
      FunctionName: !Ref SolutionsLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5

  KPILambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyKPIQueue.Arn
      FunctionName: !Ref KPILambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5

  UsecaseLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyUsecaseQueue.Arn
      FunctionName: !Ref UsecaseLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5

  BusinessAreaLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyBusinessAreasQueue.Arn
      FunctionName: !Ref BusinessAreaLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5

  IndustriesLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyIndustryQueue.Arn
      FunctionName: !Ref IndustriesLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 5
  
  LogoLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyLogoQueue.Arn
      FunctionName: !Ref LogoLambda
      BatchSize: 1
      ScalingConfig:
        MaximumConcurrency: 10


        
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SolutionsLambda}"
      RetentionInDays: 7

  TasksLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TasksLambda}"
      RetentionInDays: 7

  KPILambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KPILambda}"
      RetentionInDays: 7

  UsecaseLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UsecaseLambda}"
      RetentionInDays: 7

  BusinessAreaLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${BusinessAreaLambda}"
      RetentionInDays: 7

  IndustriesLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${IndustriesLambda}"
      RetentionInDays: 7

  LogoLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LogoLambda}"
      RetentionInDays: 7


Outputs:
  QueueURL:
    Description: URL of the created SQS Queue
    Value: !Ref MySQSQueue
  QueueARN:
    Description: ARN of the created SQS Queue
    Value: !GetAtt MySQSQueue.Arn
  TasksQueueURL:
    Description: URL of the created Tasks SQS Queue
    Value: !Ref MyTasksQueue
  TasksQueueARN:
    Description: ARN of the created Tasks SQS Queue
    Value: !GetAtt MyTasksQueue.Arn
  LambdaFunctionARN:
    Description: ARN of the Lambda Function
    Value: !GetAtt SolutionsLambda.Arn
  SQSLogGroupARN:
    Description: ARN of the CloudWatch Log Group for SQS
    Value: !GetAtt SQSLogGroup.Arn
  TasksLambdaFunctionARN:
    Description: ARN of the Tasks Lambda Function
    Value: !GetAtt TasksLambda.Arn
  KPIQueueURL:
    Description: URL of the created KPI SQS Queue
    Value: !Ref MyKPIQueue
  KPIQueueARN:
    Description: ARN of the created KPI SQS Queue
    Value: !GetAtt MyKPIQueue.Arn
  KPILambdaFunctionARN:
    Description: ARN of the KPI Lambda Function
    Value: !GetAtt KPILambda.Arn
  UsecaseQueueURL:
    Description: URL of the created Usecase SQS Queue
    Value: !Ref MyUsecaseQueue
  UsecaseQueueARN:
    Description: ARN of the created Usecase SQS Queue
    Value: !GetAtt MyUsecaseQueue.Arn
  UsecaseLambdaFunctionARN:
    Description: ARN of the Usecase Lambda Function
    Value: !GetAtt UsecaseLambda.Arn
  BusinessAreasQueueURL:
    Description: URL of the created Business Areas SQS Queue
    Value: !Ref MyBusinessAreasQueue
  BusinessAreasQueueARN:
    Description: ARN of the created Business Areas SQS Queue
    Value: !GetAtt MyBusinessAreasQueue.Arn
  BusinessAreaLambdaFunctionARN:
    Description: ARN of the Business Area Lambda Function
    Value: !GetAtt BusinessAreaLambda.Arn
  IndustryQueueURL:
    Description: URL of the created Industry SQS Queue
    Value: !Ref MyIndustryQueue
  IndustryQueueARN:
    Description: ARN of the created Industry SQS Queue
    Value: !GetAtt MyIndustryQueue.Arn
  IndustriesLambdaFunctionARN:
    Description: ARN of the Industries Lambda Function
    Value: !GetAtt IndustriesLambda.Arn
  LogoQueueURL:
    Description: URL of the created Logo SQS Queue
    Value: !Ref MyLogoQueue
  LogoQueueARN:
    Description: ARN of the created Logo SQS Queue
    Value: !GetAtt MyLogoQueue.Arn
  LogoLambdaFunctionARN:
    Description: ARN of the Logo Lambda Function
    Value: !GetAtt LogoLambda.Arn